### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by umsh315** [legion1581/go2_webrtc_connect#1]
Hello. Thank you very much for releasing such an excellent document. I have referred to various documents related to GO2 communication, but most of them did not work well, and I think the problem might be with my environment setup. I would like to use your document as well. While setting up, I encountered an error during the "pip install -e ." step. When I asked ChatGPT, it recommended installing portaudio19-dev, and after executing that, everything went well. This is my error report.

![image](https://github.com/user-attachments/assets/9e7c1f62-55a4-49b5-9509-334ebb36b964)

**Comment by umsh315** [comment]
The above error occurred when running in ROS2 Foxy, and the same error occurred in Humble as well.

![Screenshot from 2024-09-09 09-41-37](https://github.com/user-attachments/assets/bd82135e-9c52-4f9a-a77b-4619f719ee9b)

**Comment by legion1581** [comment]
Thanks! Added portaudio19-dev installation to Readme.md
