### ISSUE TITLE
How to use lidar_stream.py

### ISSUE THREAD

**Issue by umsh315** [legion1581/go2_webrtc_connect#2]
Hello. I have a question regarding data_channel/lidar. I am a beginner when it comes to communication with robots, so I apologize if my question is based on my limited knowledge, but I would appreciate your help. Currently, I am aiming to use wireless communication to visualize point cloud data on an external PC. At the moment, both the Unitree Go2 EDU and the PC are connected to the same Wi-Fi network, and I am able to establish an SSH connection. In this case, when executing the project, would it be correct to modify lidar_stream.py to conn=Go2WebRTCConnection(WebRTCConnectionMethod.LocalSTA, ip="192.168.0.90") and run it? The IP address "192.168.0.90" is the one I use to SSH into the robot over Wi-Fi. When I executed it with this setup, I only received the following output. I would appreciate any feedback you can provide.
![Screenshot from 2024-09-10 08-30-21](https://github.com/user-attachments/assets/3da1c661-e69e-406e-9f05-cbc36b258078)

**Comment by umsh315** [comment]
I used the official Go2 app to establish an STA-T connection, entered the serial number, email, and password, but the result was the same.

**Comment by legion1581** [comment]
I assume 192.168.0.90 is the IP of the GO2 EDU payload with the Wi-Fi dongle? You will need the IP of the Go2's internal computer. You can find it by navigating to Device -> Data -> Automatic Machine Inspection. Also try specifying just the serial number like this: Go2WebRTCConnection(WebRTCConnectionMethod.LocalSTA, serialNumber="B42D2000XXXXXXXX").

**Comment by umsh315** [comment]
Thank you for your response. Your interpretation of the IP address I am using is correct. I will try both solutions by the end of today.

**Comment by umsh315** [comment]
Thank you. It seems to be working well when I used the internal IP address. However, only logs are displayed, and there are no other behaviors observed. Is this the correct behavior, or is it possible that rendering is not working due to the settings on my PC?
![Screenshot from 2024-09-11 13-35-18](https://github.com/user-attachments/assets/b88789ba-89cf-4e87-a59b-2bdbd9ee58f1)
![Screenshot from 2024-09-11 13-35-02](https://github.com/user-attachments/assets/2f3314cf-6b31-4995-b0dd-1eeedb27c3c1)

**Comment by legion1581** [comment]
Yes, that’s the correct behavior. You’re receiving the decoded LiDAR data and video frames in the second screenshot. I’ll add more examples later on. Essentially, you can use any features available in the Unitree Go app through this WebRTC client, primarily for high-level commands.

**Comment by umsh315** [comment]
I wasn't able to use other repositories utilizing WebRTC before, so I am very happy to confirm that the connection is working. Thank you so much for your support! I hope that future updates will also go smoothly!
