### ISSUE TITLE
Failed to establish a new connection.

### ISSUE THREAD

**Issue by wcode-wzx** [legion1581/go2_webrtc_connect#3]
I installed the environment according to the tutorial and got an error when executing the test case. I would like to ask what the problem is. Thank you very much.

My device:
go2-edu
STA-T wifi mode

Error log：
~/alg/go2_webrtc_connect/examples/audio/mp3_player$ python play_mp3.py 
🕒 WebRTC connection        : 🟡 started       (14:54:50)
INFO:root:Creating offer...
🕒 Signaling State          : 🟡 have-local-offer (14:54:50)
🕒 ICE Gathering State      : 🟡 gathering     (14:54:50)
🕒 ICE Gathering State      : 🟢 complete      (14:54:50)
INFO:root:Trying to send SDP using the old method...
ERROR:root:An error occurred: HTTPConnectionPool(host='10.30.2.245', port=8081): Max retries exceeded with url: /offer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff769044c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR:root:An error occurred with the old method: Failed to receive SDP Answer: No response
INFO:root:Falling back to the new method...
INFO:root:SDP successfully sent using the new method.
🕒 ICE Connection State     : 🔵 checking      (14:54:50)
🕒 Peer Connection State    : 🔵 connecting    (14:54:50)
INFO:root:Track recieved: audio
INFO:root:Track recieved: video
🕒 Signaling State          : 🟢 stable        (14:54:50)
INFO:aioice.ice:Connection(1) Check CandidatePair(('10.30.2.210', 56221) -> ('10.30.2.245', 42591)) State.FROZEN -> State.IN_PROGRESS
INFO:aioice.ice:Connection(1) Check CandidatePair(('10.30.2.210', 56221) -> ('10.30.2.245', 42591)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:aioice.ice:Connection(1) Check CandidatePair(('10.30.2.210', 56221) -> ('169.254.107.33', 42224)) State.FROZEN -> State.FAILED
INFO:aioice.ice:Connection(1) Check CandidatePair(('10.30.2.210', 56221) -> ('192.168.123.161', 44945)) State.FROZEN -> State.FAILED
INFO:aioice.ice:Connection(1) ICE completed
🕒 ICE Connection State     : 🟢 completed     (14:54:50)
ERROR:root:Data channel did not open in time
INFO:root:Playing MP3: dora-doradura-mp3.mp3
INFO:aioice.ice:Connection(1) Consent to send expired
🕒 Peer Connection State    : 🔴 failed        (14:55:29)
🕒 ICE Connection State     : 🔴 failed        (14:55:29)

**Comment by legion1581** [comment]
It could be that you were using the Unitree Go APP simultaneously with this repo. I have pushed a commit to help determine that. If this doesn’t help, switch to DEBUG level and check if you are receiving SDP from the peer at this line: INFO:root:SDP successfully sent using the new method.

**Comment by wcode-wzx** [comment]
Thank you very much, solved it.

**Comment by jouzhang** [comment]
> Thank you very much, solved it.

I have the same problem. Can you tell me how to solve it?
