### ISSUE TITLE
display_video_channel.py opencv imshow does not work issue

### ISSUE THREAD

**Issue by tomotake** [legion1581/go2_webrtc_connect#4]
I create a new python program and can show the image. It does look like some of the import already block the cv2.imshow() however, once I created imshow window first, contents modification does work wihtout issue.

I hope it helps.

import cv2
import numpy as np

height, width = 720, 1280  # You can adjust the size
img = np.zeros((height, width, 3), dtype=np.uint8)
cv2.imshow('b', img)
print(f"Shape: {img.shape}, Dimensions: {img.ndim}, Type: {img.dtype}, Size: {img.size}")
cv2.waitKey(1)

from display_video_channel import main
main()

**Comment by tfoldi** [comment]
can you check #5?

**Comment by tomotake** [comment]
Sure, I will.
I am using spot from boston dynamics, and their sdk uses threading for async io (WebRTC).

**Comment by legion1581** [comment]
Thanks! Now the display_video_channel example works!
