### ISSUE TITLE
Can't connect using all different methods

### ISSUE THREAD

**Issue by dvelho** [legion1581/go2_webrtc_connect#8]
Hi I've tried with all different connection types and all of them give me the following output:
I have a Pro, firmware 1.1.1
🕒 WebRTC connection        : 🟡 started       (16:44:11)
🕒 Signaling State          : 🟡 have-local-offer (16:44:13)
🕒 ICE Gathering State      : 🟡 gathering     (16:44:13)
🕒 ICE Gathering State      : 🟢 complete      (16:44:13)
🕒 ICE Connection State     : 🔵 checking      (16:44:15)
🕒 Peer Connection State    : 🔵 connecting    (16:44:15)
🕒 Signaling State          : 🟢 stable        (16:44:15)
🕒 ICE Connection State     : 🟢 completed     (16:44:15)
Data channel did not open in time

Can you please advise?

Thanks in advance

**Comment by legion1581** [comment]
You should follow the installation procedure in the Readme.md file. The key point is to use "git clone --recurse-submodules," as this will install the forked aioice library

**Comment by dvelho** [comment]
Thank you! It worked :)

**Comment by rafaelmoraes33** [comment]
> You should follow the installation procedure in the Readme.md file. The key point is to use "git clone --recurse-submodules," as this will install the forked aioice library

Thanks to return!!

But I didn't find it in Readme.md, could you send me step by step please. It will help me a lot.

**Comment by rafaelmoraes33** [comment]
> git clone --recurse-submodules


Thank you! It worked :)
