### ISSUE TITLE
Data channel did not open in time

### ISSUE THREAD

**Issue by tsh9l** [legion1581/go2_webrtc_connect#9]
So the script runs perfectly for few hours as i was testing some of the function, running my custom script on top of the example files.
But it stopped working and even after using the fresh git clone version and rebooting router, robots and computer.

My connection method is through Local STA, by specifying my IP address. When I run the display_video_channel.py under examples/video/camera_stream, i received error:

`Data channel did not open in time`
`Backend TkAgg is interactive backend. Turning interactive mode on.`

and here is the console with logging enabled in webrtc_driver.py:
`tsehei@robotics:~/go2_webrtc_connect$  cd /home/tsehei/go2_webrtc_connect ; /usr/bin/env /usr/bin/python3.10 /home/tsehei/.vscode/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 39073 -- /home/tsehei/go2_webrtc_connect/examples/video/camera_stream/display_video_channel.py `
`🕒 WebRTC connection        : 🟡 started       (14:19:13)`
`INFO:root:Creating offer...`
`🕒 Signaling State          : 🟡 have-local-offer (14:19:13)`
`🕒 ICE Gathering State      : 🟡 gathering     (14:19:13)`
`🕒 ICE Gathering State      : 🟢 complete      (14:19:13)`
`INFO:root:Trying to send SDP using the old method...`
`ERROR:root:An error occurred: HTTPConnectionPool(host='192.168.0.120', port=8081): Max retries exceeded with url: /offer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ed8a55c0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))`
`ERROR:root:An error occurred with the old method: Failed to receive SDP Answer: No response`
`INFO:root:Falling back to the new method...`
`INFO:root:SDP successfully sent using the new method.`
`🕒 ICE Connection State     : 🔵 checking      (14:19:13)`
`INFO:root:ICE connection state changed: connecting`
`🕒 Peer Connection State    : 🔵 connecting    (14:19:13)`
`INFO:root:Track recieved: audio`
`INFO:root:Track recieved: video`
`🕒 Signaling State          : 🟢 stable        (14:19:13)`
`INFO:aioice.ice:Connection(1) Check CandidatePair(('192.168.123.222', 51020) -> ('192.168.0.120', 48257)) State.FROZEN -> State.IN_PROGRESS`
`INFO:aioice.ice:Connection(1) Check CandidatePair(('192.168.123.222', 51020) -> ('192.168.0.120', 48257)) State.IN_PROGRESS -> State.SUCCEEDED`
`INFO:aioice.ice:Connection(1) Check CandidatePair(('192.168.0.115', 54262) -> ('192.168.0.120', 48257)) State.FROZEN -> State.FAILED`
`INFO:aioice.ice:Connection(1) Check CandidatePair(('10.145.62.1', 48423) -> ('192.168.0.120', 48257)) State.FROZEN -> State.FAILED`
`INFO:aioice.ice:Connection(1) Check CandidatePair(('192.168.123.222', 51020) -> ('169.254.107.33', 37552)) State.FROZEN -> State.FAILED`
`INFO:aioice.ice:Connection(1) Check CandidatePair(('192.168.0.115', 54262) -> ('169.254.107.33', 37552)) State.FROZEN -> State.FAILED`
`INFO:aioice.ice:Connection(1) Check CandidatePair(('10.145.62.1', 48423) -> ('169.254.107.33', 37552)) State.FROZEN -> State.FAILED`
`INFO:aioice.ice:Connection(1) Check CandidatePair(('192.168.123.222', 51020) -> ('192.168.123.161', 40002)) State.FROZEN -> State.FAILED`
`INFO:aioice.ice:Connection(1) Check CandidatePair(('192.168.0.115', 54262) -> ('192.168.123.161', 40002)) State.FROZEN -> State.FAILED`
`INFO:aioice.ice:Connection(1) Check CandidatePair(('10.145.62.1', 48423) -> ('192.168.123.161', 40002)) State.FROZEN -> State.FAILED`
`INFO:aioice.ice:Connection(1) ICE completed`
`🕒 ICE Connection State     : 🟢 completed     (14:19:13)`
`Data channel did not open in time`

**Comment by PowZone** [comment]
Same issue. I'm connecting via ip too.

**Comment by tsh9l** [comment]
follow read.me, especially the part "git clone --recursive"
